# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 07:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('telentapp', '0004_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 14, 7, 18, 17, 849739, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 14, 7, 18, 27, 869214, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
