# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telentapp', '0006_auto_20160114_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telentapp.Image'),
        ),
    ]
