# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telentapp', '0007_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.SlugField(default='abcdefg'),
            preserve_default=False,
        ),
    ]
