# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 12:27
from __future__ import unicode_literals

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('telentapp', '0008_image_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='location',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
    ]
