# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telentapp', '0009_image_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
