# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telentapp', '0011_imagereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imagereport',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
