# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 15:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('telentapp', '0012_auto_20160118_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagereport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 18, 15, 4, 57, 893276, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagereport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 1, 18, 15, 5, 3, 173639, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
