# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 09:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telentapp', '0013_auto_20160118_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('action', models.TextField()),
                ('before_action', models.TextField(null=True)),
                ('after_action', models.TextField(null=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='image',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='imagelog',
            name='image_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telentapp.Image'),
        ),
        migrations.AddField(
            model_name='imagelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
