# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telentapp', '0014_auto_20160119_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='over_18',
            field=models.BooleanField(default=False),
        ),
    ]
