# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 13:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telentapp', '0019_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
